site_name: Syncwave
site_url: https://iannitello.github.io/syncwave/

theme:
  name: material
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/circle-half-full
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    primary: cyan
    accent: cyan
    toggle:
      icon: material/circle
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: cyan
    toggle:
      icon: material/circle-outline
      name: Switch to system preference

  features:
  - content.code.copy
  - content.code.annotate
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.path
  - navigation.indexes
  - navigation.top
  - toc.follow
  - search.suggest

  favicon: "favicon.png"
  logo: "white-icon.svg"

repo_name: syncwave
repo_url: https://github.com/iannitello/syncwave

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        inventories:
        - url: https://docs.python.org/3/objects.inv
          domains: [py, std]
        - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv
        - url: https://docs.pydantic.dev/latest/objects.inv
          base_url: https://docs.pydantic.dev/latest/
        options:
          # headings
          show_root_heading: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # members
          members_order: source
          # docstring
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          docstring_section_style: spacy
          # signature
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true

nav:
- Get Started:
  - Index: index.md
- Usage:
  - Syncwave: usage/syncwave.md
  - Reactivity: usage/reactivity.md
- API Reference:
  - Syncwave: api/syncwave.md
  - SyncCollection: api/sync_collections.md
  - SyncModel: api/sync_model.md
- Examples:
  - First Example: examples/first.md


markdown_extensions:
# Python Markdown
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- toc:
    permalink: true

# Python Markdown Extensions
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
